version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog_backend
    ports:
      - "3000:3000"
    working_dir: /app
    environment:
      - PORT=3000
    command: ["node", "index.js"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blog_frontend
    ports:
      - "5173:5173"
    working_dir: /app
    command: ["npm", "run", "dev"]